spring:
  datasource:
    url: jdbc:mysql://localhost:3306/liveChart?charset=utf8mb4
    username: root
    password: lwx130YI
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0

file:
  dist: E:/Augenstetn/AllProject/LiveChat/files