server:
  port: 8080

spring:
  profiles:
    active: dev
#    active: prod # 打包
  application:
    name: live-chat
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 125MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true
    database: mysql
    open-in-view: false